// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using StudentService.Data;

#nullable disable

namespace StudentService.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260425200550_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        #pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("StudentService.Models.College", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Colleges");
            });

        modelBuilder.Entity("StudentService.Models.Governorate", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Governorates");
            });

        modelBuilder.Entity("StudentService.Models.Student", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("CollegeId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int>("GovernorateId")
                    .HasColumnType("int");

                b.Property<string>("NationalId")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nationality")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("UniversityId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Village")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("CollegeId");

                b.HasIndex("GovernorateId");

                b.HasIndex("UserId")
                    .IsUnique();

                b.ToTable("Students");
            });

        modelBuilder.Entity("StudentService.Models.Student", b =>
            {
                b.HasOne("StudentService.Models.College", "College")
                    .WithMany("Students")
                    .HasForeignKey("CollegeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("StudentService.Models.Governorate", "Governorate")
                    .WithMany()
                    .HasForeignKey("GovernorateId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("College");

                b.Navigation("Governorate");
            });

        modelBuilder.Entity("StudentService.Models.College", b =>
            {
                b.Navigation("Students");
            });
        #pragma warning restore 612, 618
    }
}
