// <auto-generated />
using AdvertisingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AdvertisingService.Migrations;

[DbContext(typeof(AdvertisingDbContext))]
[Migration("20250101000000_InitialCreate")]
public partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        modelBuilder.Entity("AdvertisingService.Models.Advertisement", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.Property<Guid>("CreatedBy")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Description")
                .HasColumnType("nvarchar(max)");

            b.Property<DateTime>("EndDate")
                .HasColumnType("datetime2");

            b.Property<string>("ImageUrl")
                .HasColumnType("nvarchar(max)");

            b.Property<bool>("IsActive")
                .HasColumnType("bit");

            b.Property<int>("Priority")
                .HasColumnType("int");

            b.Property<DateTime>("StartDate")
                .HasColumnType("datetime2");

            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.Property<int>("TargetGender")
                .HasColumnType("int");

            b.Property<int>("Type")
                .HasColumnType("int");

            b.HasKey("Id");

            b.HasIndex("EndDate");

            b.HasIndex("IsActive");

            b.HasIndex("StartDate");

            b.ToTable("Advertisements");
        });

        modelBuilder.Entity("AdvertisingService.Models.AdvertisementCollege", b =>
        {
            b.Property<Guid>("AdvertisementId")
                .HasColumnType("uniqueidentifier");

            b.Property<int>("CollegeId")
                .HasColumnType("int");

            b.HasKey("AdvertisementId", "CollegeId");

            b.HasIndex("AdvertisementId");

            b.ToTable("AdvertisementColleges");
        });

        modelBuilder.Entity("AdvertisingService.Models.AdvertisementGovernorate", b =>
        {
            b.Property<Guid>("AdvertisementId")
                .HasColumnType("uniqueidentifier");

            b.Property<int>("GovernorateId")
                .HasColumnType("int");

            b.HasKey("AdvertisementId", "GovernorateId");

            b.HasIndex("AdvertisementId");

            b.ToTable("AdvertisementGovernorates");
        });

        modelBuilder.Entity("AdvertisingService.Models.AdvertisementCollege", b =>
        {
            b.HasOne("AdvertisingService.Models.Advertisement", "Advertisement")
                .WithMany("AdvertisementColleges")
                .HasForeignKey("AdvertisementId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Advertisement");
        });

        modelBuilder.Entity("AdvertisingService.Models.AdvertisementGovernorate", b =>
        {
            b.HasOne("AdvertisingService.Models.Advertisement", "Advertisement")
                .WithMany("AdvertisementGovernorates")
                .HasForeignKey("AdvertisementId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Advertisement");
        });

        modelBuilder.Entity("AdvertisingService.Models.Advertisement", b =>
        {
            b.Navigation("AdvertisementColleges");

            b.Navigation("AdvertisementGovernorates");
        });
    }
}
