// <auto-generated />
using System;
using AdvertisingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvertisingService.Migrations
{
    [DbContext(typeof(AdvertisingDbContext))]
    partial class AdvertisingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdvertisingService.Models.Advertisement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TargetGender")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartDate");

                    b.ToTable("Advertisements", (string)null);
                });

            modelBuilder.Entity("AdvertisingService.Models.AdvertisementCollege", b =>
                {
                    b.Property<Guid>("AdvertisementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.HasKey("AdvertisementId", "CollegeId");

                    b.ToTable("AdvertisementColleges", (string)null);
                });

            modelBuilder.Entity("AdvertisingService.Models.AdvertisementGovernorate", b =>
                {
                    b.Property<Guid>("AdvertisementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.HasKey("AdvertisementId", "GovernorateId");

                    b.ToTable("AdvertisementGovernorates", (string)null);
                });

            modelBuilder.Entity("AdvertisingService.Models.AdvertisementCollege", b =>
                {
                    b.HasOne("AdvertisingService.Models.Advertisement", "Advertisement")
                        .WithMany("AdvertisementColleges")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("AdvertisingService.Models.AdvertisementGovernorate", b =>
                {
                    b.HasOne("AdvertisingService.Models.Advertisement", "Advertisement")
                        .WithMany("AdvertisementGovernorates")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("AdvertisingService.Models.Advertisement", b =>
                {
                    b.Navigation("AdvertisementColleges");

                    b.Navigation("AdvertisementGovernorates");
                });
#pragma warning restore 612, 618
        }
    }
}
